import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { ReduxProvider } from "@/lib/redux/ReduxProvider";
import StatusBarSetter from "@/components/StatusBarSetter";
import SplashScreen from "@/components/SplashScreen";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: `
            /* Hide scrollbars completely on Android WebView */
            * {
              -ms-overflow-style: none !important;
              scrollbar-width: none !important;
            }
            *::-webkit-scrollbar {
              display: none !important;
              width: 0 !important;
              height: 0 !important;
              background: transparent !important;
            }
            *::-webkit-scrollbar-track {
              display: none !important;
              background: transparent !important;
              width: 0 !important;
              height: 0 !important;
            }
            *::-webkit-scrollbar-thumb {
              display: none !important;
              background: transparent !important;
              width: 0 !important;
              height: 0 !important;
            }
            *::-webkit-scrollbar-button {
              display: none !important;
              width: 0 !important;
              height: 0 !important;
            }
            *::-webkit-scrollbar-corner {
              display: none !important;
              background: transparent !important;
            }
            html, body {
              -ms-overflow-style: none !important;
              scrollbar-width: none !important;
              overflow-x: hidden !important;
              overscroll-behavior: none !important;
              overscroll-behavior-y: none !important;
              overscroll-behavior-x: none !important;
              background-color: #000000 !important;
            }
            html::-webkit-scrollbar, body::-webkit-scrollbar {
              display: none !important;
              width: 0 !important;
              height: 0 !important;
              background: transparent !important;
            }
          `,
          }}
        />
      </head>
      <body className="antialiased overflow-x-hidden">
        <SplashScreen>
          <ReduxProvider>
            <AuthProvider>
              <StatusBarSetter />
              {children}
            </AuthProvider>
          </ReduxProvider>
        </SplashScreen>
      </body>
    </html>
  );
}
